# Generated by Django 5.2.15 on 2026-06-03 20:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Auto-generated key the IDE plugin sends in X-API-Key header.', unique=True)),
                ('timezone', models.CharField(default='UTC', help_text="IANA timezone, e.g. 'Asia/Kolkata'.", max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this account was provisioned.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CodingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Computed on session close or periodically while active.')),
                ('editor', models.CharField(default='unknown', help_text="Editor identifier, e.g. 'vscode', 'neovim'.", max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Flipped to False when the session closes.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CodeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('file_save', 'File Save'), ('file_open', 'File Open'), ('file_close', 'File Close'), ('keystroke_batch', 'Keystroke Batch')], max_length=32)),
                ('file_path', models.CharField(max_length=512)),
                ('language', models.CharField(default='unknown', help_text='Detected programming language of the file.', max_length=64)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_events', to='telemetry.codingsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('file_path', models.CharField(blank=True, default='', max_length=512)),
                ('language', models.CharField(default='unknown', max_length=64)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(default='unknown', help_text="Where the error came from: 'linter', 'compiler', 'runtime', etc.", max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='error', max_length=16)),
                ('resolved', models.BooleanField(default=False, help_text='Marked True when the error no longer appears in diagnostics.')),
                ('resolution_time_seconds', models.PositiveIntegerField(blank=True, help_text='Seconds between the error appearing and being resolved.', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_events', to='telemetry.codingsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('commit', 'Commit'), ('push', 'Push'), ('pull', 'Pull'), ('branch_switch', 'Branch Switch'), ('merge', 'Merge')], max_length=32)),
                ('branch', models.CharField(default='', max_length=255)),
                ('files_changed', models.PositiveIntegerField(default=0)),
                ('insertions', models.PositiveIntegerField(default=0)),
                ('deletions', models.PositiveIntegerField(default=0)),
                ('commit_hash', models.CharField(blank=True, default='', max_length=64)),
                ('message', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_events', to='telemetry.codingsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SkillSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=64)),
                ('framework', models.CharField(blank=True, help_text="Optional framework, e.g. 'Django', 'React'.", max_length=128, null=True)),
                ('proficiency_score', models.FloatField(help_text='0–100 proficiency score produced by the LLM agent.')),
                ('evidence', models.JSONField(default=dict, help_text='Supporting data the agent used to derive the score.')),
                ('period', models.CharField(help_text="ISO week like '2024-W01' or month like '2024-01'.", max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerminalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=1024)),
                ('exit_code', models.IntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='How long the command took to execute in milliseconds.')),
                ('shell', models.CharField(default='unknown', help_text="Shell type, e.g. 'bash', 'zsh', 'powershell'.", max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_events', to='telemetry.codingsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('report_data', models.JSONField(default=dict, help_text='Full structured report (highlights, badges, tips, etc.).')),
                ('summary', models.TextField(blank=True, default='', help_text='Human-readable narrative summary.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('skill', 'Skill'), ('productivity', 'Productivity'), ('debug', 'Debug'), ('career', 'Career'), ('anomaly', 'Anomaly')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=16)),
                ('actionable', models.BooleanField(default=False, help_text='True if the insight contains a concrete action the dev can take.')),
                ('metadata', models.JSONField(default=dict, help_text='Freeform data the agent attaches for the frontend to render.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'insight_type', 'created_at'], name='idx_insight_user_type_ts')],
            },
        ),
        migrations.AddIndex(
            model_name='codingsession',
            index=models.Index(fields=['user', 'start_time'], name='idx_session_user_start'),
        ),
        migrations.AddIndex(
            model_name='codeevent',
            index=models.Index(fields=['session', 'timestamp'], name='idx_code_session_ts'),
        ),
        migrations.AddIndex(
            model_name='codeevent',
            index=models.Index(fields=['language'], name='idx_code_language'),
        ),
        migrations.AddIndex(
            model_name='errorevent',
            index=models.Index(fields=['session', 'timestamp'], name='idx_err_session_ts'),
        ),
        migrations.AddIndex(
            model_name='errorevent',
            index=models.Index(fields=['resolved'], name='idx_err_resolved'),
        ),
        migrations.AddIndex(
            model_name='gitevent',
            index=models.Index(fields=['session', 'timestamp'], name='idx_git_session_ts'),
        ),
        migrations.AlterUniqueTogether(
            name='skillsnapshot',
            unique_together={('user', 'language', 'period')},
        ),
        migrations.AddIndex(
            model_name='terminalevent',
            index=models.Index(fields=['session', 'timestamp'], name='idx_term_session_ts'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together={('user', 'week_start')},
        ),
    ]
